### PR TITLE
Fixing external links not redirecting properly

### LINKED ISSUE #82: Enhancement: fix footer links
### Describe the Current Behavior/Feature:

Footer currently does not actual destinations in `socialLinks` section.
codepdx in legalLinks goes to website url, it should scroll to top of home page.

---

### Proposed Implementation:

- Add proper destination to each link and make sure they are recognized in DOM as links

### PR DESCRIPTION
**Pull request by andycwilliams**
## This PR:

Resolves #82 

Doesn't directly address that issue, since much of it was already finished. However, the social media links in the footer still needed to be fixed. So these kind of dovetail and that can finally be closed once this is done.

Currently they don't actually direct to the websites they're pointed to. I removed `component={ReactRouterLink}` from the social media `Link` component, which for me fixes the issue. 

## Future Steps/PRs Needed to Finish This Work (optional):

Test it and make sure it works on other devices and browsers.

Also, we discussed having a separate `development` branch for working with, rather than using the main branch itself. I can create one now and then change this PR so it merges with that, if we want.

### CODE REVIEW

**Review by Jared-Krajewski — CHANGES_REQUESTED** [review]
I'm not sure this PR fixes anything. The issue in question is regarding the legal links which I had quickly fixed before hosting the site. Footer links should be working prior to this PR with the exception of the socialLinks that all point back to the website. The only change in this PR removes `component={ReactRouterLink}` from the social links which technically does nothing since they are all external links. It can still be removed but this issue should include fixing the social links as well. I updated the issue to reflect this.

**Comment by andycwilliams** [comment]
When I test it, the social media links just point back to the website yet removing just `component={ReactRouterLink}` resolves the issue. So at least for my machine it does fix them.

**Comment by Jared-Krajewski** [comment]
> When I test it, the social media links just point back to the website yet removing just `component={ReactRouterLink}` resolves the issue. So at least for my machine it does fix them.

Interesting. When I checked it again, that does fix it. Maybe I had a page load error when I tested it before. Not sure if you had a chance to see updated issue. If you can add codePDX linking to top of home page this is good to go.

**Comment by andycwilliams** [comment]
> > When I test it, the social media links just point back to the website yet removing just `component={ReactRouterLink}` resolves the issue. So at least for my machine it does fix them.
> 
> Interesting. When I checked it again, that does fix it. Maybe I had a page load error when I tested it before.

Just tested some more. I believe it's due to how the `Link` component for social media uses `href={href}` whereas the one for legal links uses `to={link.href}` instead. When I change the legal links to also use `href={href}` (while keeping the react router link component), it breaks the links and redirects them to the website just like the social media links.

I can leave it as is, or change one so it matches the other. I don't know if using `href` is better than `to` or vice versa, or if it matters.

**Comment by andycwilliams** [comment]
Not sure if I overengineered it, but the button should navigate to the top of the homepage now.

Also I removed the `reactRouterLink` import because by changing how the `Link`s are set up, it is no longer necessary. They now use `href` but I can change it to `to` instead if preferred. Then `reactRouterLink` would need to be added back.

File: src/components/global/Footer.jsx [hunk 1]
```diff
@@ -1,5 +1,5 @@
 // React Router Imports
-import { Link as ReactRouterLink } from 'react-router-dom';
+import { useNavigate } from 'react-router-dom';
```
Comment (Jared-Krajewski) [inline src/components/global/Footer.jsx]: not necessary, theres no real internal routing going on here. the code pdx just scrolls to top and is the only internal link.

File: src/components/global/Footer.jsx [hunk 2]
```diff
@@ -79,41 +74,50 @@ const renderSocialLinks = socialMediaLinks.map(({ ariaLabel, href, icon }) => (
...
-      <Link
-        component={ReactRouterLink}
-        to={link.href}
-        target="_blank"
-        rel="noopener noreferrer"
-        underline="none"
-        aria-label={`${link.title}`}
-        ml={link.ml ?? null}
+// Maps legalLinks used for placement in stack below
+const renderLegalLinks = (navigate) => {
```
Comment (Jared-Krajewski) [inline src/components/global/Footer.jsx]: `navigate` arg can be removed

File: src/components/global/Footer.jsx [hunk 3]
```diff
@@ -163,11 +167,12 @@ const footerContainerStyle = (theme) => ({
 
 const Footer = () => {
   const theme = useTheme();
+  const navigate = useNavigate();
```
Comment (Jared-Krajewski) [inline src/components/global/Footer.jsx]: can be removed.

File: src/components/global/Footer.jsx [hunk 4]
```diff
@@ -200,7 +205,7 @@ const Footer = () => {
           }
         }}
       >
-        {renderLegalLinks}
+        {renderLegalLinks(navigate)}
```
Comment (Jared-Krajewski) [inline src/components/global/Footer.jsx]: should work fine with just `{renderLegalLinks()}`

File: src/components/global/Footer.jsx [hunk 5]
```diff
@@ -79,41 +74,50 @@ const renderSocialLinks = socialMediaLinks.map(({ ariaLabel, href, icon }) => (
...
+            color: '#000',
+            '&:hover': {
+              color: 'primary.main'
+            }
+          }}
+          onClick={
+            link.title === 'CODE PDX'
+              ? (event) => {
+                  event.preventDefault();
+                  navigate('/');
```
Comment (Jared-Krajewski) [inline src/components/global/Footer.jsx]: `navigate('/');` can be removed, the scroll to top takes care of that links functionality since it stays on same page.

**Review by Jared-Krajewski — CHANGES_REQUESTED** [review]
some extra code that can be removed, then should be good to go.

**Comment by andycwilliams** [comment]
@Jared-Krajewski It looks like the Discord invite is invalid. It's telling me it might be expired or I may not have permission to join.

I'm testing it on different browsers, where I'm not already logged in, and it's the same.

**Comment by Jared-Krajewski** [comment]
> @Jared-Krajewski It looks like the Discord invite is invalid. It's telling me it might be expired or I may not have permission to join.
> 
> I'm testing it on different browsers, where I'm not already logged in, and it's the same.

interesting, it was working for me. I can make yet another new invite and push it. Does that mean the discord link in the volunteer section is also broken for you? (test on live site) not sure why invites that 'dont' expire, keep expiring. Going to push new links and call this good to merge.

**Review by Jared-Krajewski — APPROVED** [review]
Good to merge, thanks.
